Разметка внутренних страниц
htmlacademy-adaptive/555-pink-24 pull request #3
Opened 2021-12-08 12:30 UTC by EtelBogen

2021-12-08 17:26 UTC, Manyaka requested changes

2021-12-08 17:26 UTC, Manyaka commented on source/form.html
> +        <fieldset class="competition__fields personal-data">
это всё отсюда и до конца формы - элементы формы. Филдсеты можно делать блоками, а можно и модами

2021-12-08 17:26 UTC, Manyaka commented on source/form.html
> +          <legend class="competition__legend">Ваши безбашенные достижения в путешествии</legend>
этот легенд выглядит как выше лейблы, так что обрати внимание на класс, которые ты на него повесишь

2021-12-08 17:26 UTC, Manyaka commented on source/form.html
> +          <ul class="competition__applications applications-list">
этот ul абсолютно идентичный ul c чекбоксами

2021-12-08 17:26 UTC, Manyaka commented on source/form.html
> +        </fieldset>
слишком жирно для одного элемента филдсет

2021-12-08 17:26 UTC, Manyaka commented on source/form.html
> +        <button class="competition__button" type="submit">Отправить форму</button>
а ты не хочешь кнопки собрать в свой блок?

2021-12-08 17:26 UTC, Manyaka commented on source/form.html
> +        <p class="competition__footnote">* — обязательные поля</p>
как ты звездочку сделаешь красной? :) Через ::first-letter?

2021-12-08 17:26 UTC, Manyaka commented on source/photo.html
> +<!DOCTYPE html>
может страницу "каталог" назвать, как в фигме? (я вообще за то, чтобы всё называлось как в фигме, тк пусть лучше диз испытывает когнитивную нагрузку в придумывании :))

2021-12-08 17:26 UTC, Manyaka commented on source/photo.html
> +      <p class="page-main__description">
ну что это слоган из формы?

2021-12-08 17:26 UTC, Manyaka commented on source/photo.html
> +        <h2 class="visually-hidden">Лента фотографий</h2>
Вот тут секция очень уместна

2021-12-08 17:26 UTC, Manyaka commented on source/form.html
> +          <textarea name="emotions__textarea" placeholder="Можно прям в красках, не
лейбл для текстарии надо добавить

2021-12-08 17:26 UTC, Manyaka commented on source/photo.html
> +            </div>
самостоятельный блок

2021-12-08 17:26 UTC, Manyaka commented on source/photo.html
> +          <li class="photos-list__item">
тут надо подумать, где ты будешь делать отступы. Если внутри лишек, то этой первой надо дать мод, чтобы типа тут не было отступов, чтобы растянуть всю картинку, но так не очень удобно.
Тогда мод будет на картинке, хотя лучше сейчас пока не делать, пусть пока первая картинка идет как все.

2021-12-08 17:26 UTC, Manyaka commented on source/photo.html
> +      <p class="page-main__description">
это опять слоган

2021-12-08 17:26 UTC, Manyaka commented on source/photo.html
> +      <section class="editor">
h2 для section

2021-12-08 17:26 UTC, Manyaka commented on source/photo.html
> +        <button class="editor__post editor__post--deactive">Отмена</button>
а ты не хочешь тут форму сделать? или времени не будет и будем делать рыбу?

2021-12-08 17:26 UTC, Manyaka commented on source/photo.html
> +        <button class="editor__post editor__post--deactive">Отмена</button>
типы кнопок

2021-12-08 17:26 UTC, Manyaka commented on source/photo.html
> +          <button class="editor__tools editor__tools--contrast editor__tools--deactive">Контраст</button>
лучше свегешками делать тогда, тк ты свг умеешь стилизовать, а кнопки в виде свг - нет. Хотя это легко через маски. Ну надо подумать. В любом случае кнопкам нужны типы. Почему? :)

2021-12-12 16:07 UTC, EtelBogen commented on source/form.html
> +          <legend class="competition__legend">Ваши безбашенные достижения в путешествии</legend>
У них разные line height, поэтому все-таки разные классы. А вот лейблы везде одинаковые, это учту. Спасибо!

2021-12-14 05:49 UTC, Manyaka requested changes

2021-12-14 05:49 UTC, Manyaka commented on source/catalog.html
> +    <header class="page-header page-header">
тебе же не просто надо мод удалить, надо же класс с модом целиком

2021-12-14 05:49 UTC, Manyaka commented on source/catalog.html
> +    <header class="page-header page-header">
поправь везде :)

2021-12-14 05:49 UTC, Manyaka commented on source/catalog.html
> +            <a href="#"><img class="photo-item__picture photo-item__picture--top" width="320" height="137" src="" alt="Фотография Анны"></a>
```suggestion
            <a href="#"><img class="photo-item__picture photo-item__picture--top" width="320" height="137" src="" alt="Фотография Анны."></a>
```

точки в альтах

2021-12-14 05:49 UTC, Manyaka commented on source/catalog.html
> +              <p class="photo-item__author">Анна <span class="photo-item__timestamp">(5 минут назад)</span></p>
```suggestion
              <p class="photo-item__author">Анна <time class="photo-item__timestamp">(5 минут назад)</time></p>
```

2021-12-14 05:59 UTC, Manyaka requested changes

2021-12-14 05:59 UTC, Manyaka commented on source/catalog.html
> +              <p class="photo-item__likes">Нравится: 215</p>
тут надо подумать, какой это будет функционал, но меня пока вполне устраивает параграф, но, допустим, в конце курса, тут можно будет и переделать. Допустим, ты подумаешь, что сердечко - это кнопка лайк/анлайк, а число 215 приходит с бека, значит ему нужен контейнер, типа спана, и в итоге ты видишь, что это уже не просто параграф, а даже уже такой маленький блочёк с функционалом лайков. Сейчас можно не править, я бы хотела, чтобы ты эту мысль просто держала на подкорке, она там у тебя пока повариться, а потом можно и переделать.

2021-12-14 05:59 UTC, Manyaka commented on source/form.html
> +            <input class="competition-data__input" id="surname" type="text" name="surname" placeholder="Укажите фамилию *">
Я говорю - это всё элементы формы. Вот, допустим, уберешь ты филдсет, тк он не флекситься, и что?, переделывать инпуты? или вставишь инпут без филдсета? Нет, все элементы формы по-русски они же элементы формы по бэму

2021-12-14 06:02 UTC, Manyaka requested changes

2021-12-14 06:02 UTC, Manyaka commented on source/catalog.html
> +          <button class="editor__tools editor__tools--fill editor__tools--deactive" type="button">Заливка</button>
```suggestion
          <button class="editor__tools editor__tools--fill editor__tools--inactive" type="button">Заливка</button>
```

неактивный = inactive

2021-12-16 05:58 UTC, Manyaka requested changes

2021-12-16 05:58 UTC, Manyaka commented on source/form.html
> +              <label class="ccompetition-form__checks-label" for="iOS">Pink для iOS</label>
```suggestion
              <label class="competition-form__checks-label" for="iOS">Pink для iOS</label>
```

2021-12-16 05:58 UTC, Manyaka commented on source/form.html
> +          <legend class="competition-form__legend">Опишите свои эмоции</legend>
Легенда не существует без филдсета

2021-12-16 13:12 UTC, merged