Стилизация всех страниц
htmlacademy-adaptive/555-pink-24 pull request #4
Opened 2022-01-09 07:45 UTC by EtelBogen

2022-01-10 08:12 UTC, Manyaka requested changes

2022-01-10 08:12 UTC, Manyaka commented on source/less/style.less
> +@import "./general/fonts.less";
Сначала было слово :) те фонты идут всегда первыми, как написано в `@font-face`
Потом идут переменные и миксины, тк они используются везде, потом уже дженерал

2022-01-10 08:12 UTC, Manyaka commented on source/less/style.less
> +// Общие блоки
отсортируй тут файлы по алфавиту, и не привязывайся к страницам, тк сайт разбивается на блоки, а не на страницы.
А сортировка по-алфавиту немного но снимет каскадность, и будет проще ослеживать независимость блоков

2022-01-10 08:37 UTC, Manyaka requested changes

2022-01-10 08:37 UTC, Manyaka commented on source/less/blocks/competition-form.less
> +.competition__contacts-data,
Блок называется `competition-form.less`, а у тебя тут свойства для другого блока: `competition`. Нужно их разнести

2022-01-10 08:37 UTC, Manyaka commented on source/less/blocks/competition-form.less
> +.achievements,
это файл блока `competition-form.less`, тут не может быть стилей для других блоков

2022-01-10 08:37 UTC, Manyaka commented on source/less/blocks/competition-form.less
> +  font-family: "OpenSans", "Arial", sans-serif;
Не хочешь сделать для фонтов переменную?
`@font-family-main: "OpenSans", "Arial", sans-serif` типа такого?

2022-01-10 08:37 UTC, Manyaka commented on source/less/blocks/editor.less
> +
пустые строки лишние, тебе можно плагин бьютифаер установить и он чистит css

2022-01-10 08:37 UTC, Manyaka commented on source/less/blocks/page-header.less
> +.page-header {
На примере этого файла хотела сказать, что тут вот отлично ты сделала, идут стили блока первыми, потом стили его элемента, и у него есть мод - он внутри - всё правильно!

2022-01-10 08:37 UTC, Manyaka commented on source/less/general/fonts.less
> +  font-weight: lighter;
А уточни вес, тк это неудобное обозначение веса. Лучше цифрами

2022-01-10 21:54 UTC, EtelBogen commented on source/less/blocks/competition-form.less
> +.competition__contacts-data,
Там вообще была у меня путаница — старые названия блоков. А по ходу стилизации кое-что меняла, когда стало понятнее, как удобнее и проще. Убрала пока вообще.

2022-01-10 21:55 UTC, EtelBogen commented on source/less/blocks/competition-form.less
> +.achievements,
Хорошенько подумала, посмотрела на версию планшетную и десктопную и вообще сделала на модификаторе цвет бэкграунда.

2022-01-12 06:28 UTC, Manyaka commented
![Снимок экрана 2022-01-12 в 09 15 09](https://user-images.githubusercontent.com/6417966/149075612-ffe34b40-ac3f-4ca4-b3bb-39458e7ff312.jpg)

2022-01-12 06:29 UTC, Manyaka commented
![Снимок экрана 2022-01-12 в 09 15 43](https://user-images.githubusercontent.com/6417966/149075642-257ff05d-36e9-42d0-91ec-c987eb0db6bd.jpg)

2022-01-12 06:29 UTC, Manyaka commented
![Снимок экрана 2022-01-12 в 09 17 18](https://user-images.githubusercontent.com/6417966/149075683-a6f928e1-9eb6-474f-8b7a-cb91edcd4b8e.jpg)

2022-01-12 06:29 UTC, Manyaka commented
![Снимок экрана 2022-01-12 в 09 18 36](https://user-images.githubusercontent.com/6417966/149075718-91c5545e-0941-4838-9e30-ee369a0e9c91.jpg)

2022-01-12 06:30 UTC, Manyaka commented
![Снимок экрана 2022-01-12 в 09 19 38](https://user-images.githubusercontent.com/6417966/149075747-3f048a81-120c-479c-be96-9406b8aff24b.jpg)

2022-01-12 06:30 UTC, Manyaka commented
![Снимок экрана 2022-01-12 в 09 20 28](https://user-images.githubusercontent.com/6417966/149075780-ff231770-1e06-4f07-b30c-0453ee4f46b4.jpg)

2022-01-12 06:30 UTC, Manyaka commented
![Снимок экрана 2022-01-12 в 09 22 26](https://user-images.githubusercontent.com/6417966/149075817-0e71232d-cfa7-4a49-ae13-ca553d2aba42.jpg)

2022-01-12 06:30 UTC, Manyaka commented
![Снимок экрана 2022-01-12 в 09 23 57](https://user-images.githubusercontent.com/6417966/149075857-16dd97a1-3ea1-466a-9c06-29c39c168a07.jpg)

2022-01-15 07:14 UTC, merged